### ISSUE TITLE
I need an executable of this, please 

### ISSUE THREAD

**Issue by Dhyfer1** [Maplespe/ColorReset#1]
Hi @Maplespe 

I am an end user, I don't know how to compile ColorReset but I want to use it, can you create an executable to use it in an easier way?

Thanks in advance

**Comment by Maplespe** [comment]
This is a toy I wrote a long time ago, it's actually very limited in what it can do, and requires a program to be launched through it to take effect.
The details are on my website:https://winmoes.com/tools/11394.html
The program is no longer maintained, I will archive it later.
[ColorReset.zip](https://github.com/Maplespe/ColorReset/files/15147824/ColorReset.zip)
